SET @failure_record_known_codes = JSON_ARRAY(
  'UNAUTHORIZED', 'FORBIDDEN', 'NOT_FOUND', 'INVALID_PARAMS', 'PAYLOAD_TOO_LARGE',
  'UPLOAD_FILE_EMPTY', 'UPLOAD_MEDIA_TYPE_UNSUPPORTED',
  'PROJECT_ASSISTANT_TEXT_ATTACHMENT_FILE_NAME_EMPTY',
  'PROJECT_ASSISTANT_TEXT_ATTACHMENT_UNSUPPORTED_TYPE',
  'PROJECT_ASSISTANT_TEXT_ATTACHMENT_EMPTY',
  'PROJECT_ASSISTANT_TEXT_ATTACHMENT_SIZE_LIMIT_EXCEEDED',
  'PROJECT_ASSISTANT_TEXT_ATTACHMENT_CHAR_LIMIT_EXCEEDED',
  'PROJECT_ASSISTANT_TEXT_ATTACHMENTS_TOO_MANY',
  'PROJECT_ASSISTANT_MEDIA_ATTACHMENT_UNSUPPORTED_TYPE',
  'PROJECT_ASSISTANT_MEDIA_ATTACHMENT_SIZE_LIMIT_EXCEEDED',
  'PROJECT_ASSISTANT_MEDIA_ATTACHMENTS_TOO_MANY',
  'OPERATION_IDEMPOTENCY_KEY_REQUIRED', 'OPERATION_IDEMPOTENCY_KEY_INVALID',
  'OPERATION_PLAN_REQUEST_REPLAY_DIVERGED',
  'WORKSPACE_RESOURCE_RETRY_TARGET_NOT_FOUND',
  'WORKSPACE_RESOURCE_RETRY_TARGET_DUPLICATE',
  'WORKSPACE_RESOURCE_RETRY_TARGET_INVALID',
  'WORKSPACE_RESOURCE_RETRY_FROZEN_INPUT_MISSING',
  'WORKSPACE_RESOURCE_RETRY_FROZEN_INPUT_AMBIGUOUS',
  'WORKSPACE_RESOURCE_RETRY_FROZEN_INPUT_INVALID',
  'WORKSPACE_RESOURCE_RETRY_FROZEN_INPUT_MISMATCH',
  'WORKSPACE_RESOURCE_RETRY_TARGET_CHANGED',
  'VOICE_RESOURCE_ALTERNATIVE_GROUP_MEMBER', 'MISSING_CONFIG', 'CONFLICT',
  'OPERATION_PLAN_CHANGED', 'TASK_NOT_READY', 'NO_RESULT', 'RATE_LIMIT',
  'MODEL_NOT_OPEN', 'MODEL_NOT_REGISTERED', 'MODEL_NOT_CONFIGURED',
  'PROVIDER_AUTH_INVALID', 'PLATFORM_PROVIDER_AUTH_INVALID',
  'PROVIDER_BILLING_REQUIRED', 'PLATFORM_PROVIDER_BILLING_REQUIRED',
  'PLATFORM_PROVIDER_UNAVAILABLE', 'QUOTA_EXCEEDED', 'EXTERNAL_ERROR',
  'NETWORK_ERROR', 'EMPTY_RESPONSE', 'MODEL_OUTPUT_TRUNCATED',
  'CONTEXT_BUDGET_EXCEEDED', 'PARSE_ERROR', 'MODEL_OUTPUT_SCHEMA_INVALID',
  'PLAN_VALIDATION_FAILED', 'PROVIDER_POLL_FAILED', 'PROVIDER_SUBMIT_FAILED',
  'PROVIDER_SUBMISSION_REJECTED', 'PROVIDER_SUBMISSION_OUTCOME_UNKNOWN',
  'INSUFFICIENT_BALANCE', 'PAID_BETA_SOLD_OUT', 'SENSITIVE_CONTENT',
  'CONTENT_RIGHTS_RESTRICTION', 'GENERATION_TIMEOUT', 'GENERATION_QUEUE_TIMEOUT',
  'VIDEO_API_FORMAT_UNSUPPORTED', 'MUSIC_PROMPT_TOO_LONG', 'GENERATION_FAILED',
  'WATCHDOG_TIMEOUT', 'WORKER_EXECUTION_ERROR', 'INTERNAL_ERROR',
  'AGENT_TEMPORAL_UNAVAILABLE', 'AGENT_THREAD_BUSY',
  'AGENT_TURN_COMMAND_REPLAY_DIVERGED', 'AGENT_STEER_HANDOFF_UNCERTAIN',
  'AGENT_START_HANDOFF_UNCERTAIN', 'PROJECT_AGENT_RUNTIME_FAILED',
  'ASSISTANT_PROVIDER_REQUEST_INVALID', 'ASSISTANT_RUNTIME_PROTOCOL_ERROR',
  'PROJECT_AGENT_ASSISTANT_MODEL_NOT_CONFIGURED',
  'PROJECT_AGENT_ASSISTANT_MODEL_INVALID', 'PROJECT_DELETE_ACTIVE_EXECUTION',
  'PROJECT_AGENT_AI_TURN_PROTOCOL_REQUIRED', 'PROJECT_AGENT_RUN_ACTIVE',
  'PROJECT_AGENT_CONTROL_ALREADY_RESOLVED',
  'PROJECT_AGENT_INTERRUPTION_NOT_PENDING',
  'PROJECT_ASSISTANT_CARD_RESPONSE_FAILED',
  'PROJECT_ASSISTANT_BACKGROUND_FOLLOW_UP_FAILED'
);

CREATE TEMPORARY TABLE `_failure_record_cutover_guard` (
  `id` INT NOT NULL PRIMARY KEY
);
INSERT INTO `_failure_record_cutover_guard` (`id`) VALUES (1);
-- Abort before any DDL if dropping the legacy Resource columns would orphan a
-- failure that has no Task owner to receive it.
INSERT INTO `_failure_record_cutover_guard` (`id`)
SELECT 1
FROM `workspace_resources` AS `resource`
LEFT JOIN `tasks` AS `task` ON `task`.`id` = `resource`.`taskId`
WHERE (`resource`.`errorCode` IS NOT NULL OR `resource`.`errorMessage` IS NOT NULL)
  AND `task`.`id` IS NULL
LIMIT 1;
DROP TEMPORARY TABLE `_failure_record_cutover_guard`;

ALTER TABLE `project_agent_turns`
  ADD COLUMN `failure` JSON NULL;

UPDATE `project_agent_turns`
SET `failure` = JSON_OBJECT(
  'version', 1,
  'code', CASE
    WHEN JSON_CONTAINS(@failure_record_known_codes, JSON_QUOTE(NULLIF(`errorCode`, '')))
      THEN `errorCode`
    ELSE 'INTERNAL_ERROR'
  END,
  'message', COALESCE(NULLIF(`errorMessage`, ''), NULLIF(`errorCode`, ''), 'Assistant runtime failed'),
  'details', CASE
    WHEN NULLIF(`errorCode`, '') IS NOT NULL
      AND NOT JSON_CONTAINS(@failure_record_known_codes, JSON_QUOTE(`errorCode`))
      THEN JSON_OBJECT('legacyCode', `errorCode`)
    ELSE NULL
  END,
  'origin', JSON_OBJECT('system', 'runtime')
)
WHERE `errorCode` IS NOT NULL OR `errorMessage` IS NOT NULL;

ALTER TABLE `project_agent_turns`
  DROP COLUMN `errorCode`,
  DROP COLUMN `errorMessage`;

ALTER TABLE `tasks`
  ADD COLUMN `failure` JSON NULL;

UPDATE `tasks`
SET `failure` = JSON_OBJECT(
  'version', 1,
  'code', CASE
    WHEN JSON_CONTAINS(@failure_record_known_codes, JSON_QUOTE(NULLIF(`errorCode`, '')))
      THEN `errorCode`
    ELSE 'INTERNAL_ERROR'
  END,
  'message', COALESCE(NULLIF(`errorMessage`, ''), NULLIF(`errorCode`, ''), 'Task failed'),
  'details', CASE
    WHEN NULLIF(`errorCode`, '') IS NOT NULL
      AND NOT JSON_CONTAINS(@failure_record_known_codes, JSON_QUOTE(`errorCode`))
      THEN JSON_OBJECT('legacyCode', `errorCode`)
    ELSE NULL
  END,
  'origin', JSON_OBJECT('system', 'application')
)
WHERE `errorCode` IS NOT NULL OR `errorMessage` IS NOT NULL;

ALTER TABLE `tasks`
  DROP COLUMN `errorCode`,
  DROP COLUMN `errorMessage`;

UPDATE `workspace_resources` AS `resource`
JOIN `tasks` AS `task` ON `task`.`id` = `resource`.`taskId`
SET `task`.`failure` = JSON_OBJECT(
  'version', 1,
  'code', CASE
    WHEN JSON_CONTAINS(@failure_record_known_codes, JSON_QUOTE(NULLIF(`resource`.`errorCode`, '')))
      THEN `resource`.`errorCode`
    ELSE 'INTERNAL_ERROR'
  END,
  'message', COALESCE(
    NULLIF(`resource`.`errorMessage`, ''),
    NULLIF(`resource`.`errorCode`, ''),
    'Task failed'
  ),
  'details', CASE
    WHEN NULLIF(`resource`.`errorCode`, '') IS NOT NULL
      AND NOT JSON_CONTAINS(
        @failure_record_known_codes,
        JSON_QUOTE(`resource`.`errorCode`)
      )
      THEN JSON_OBJECT('legacyCode', `resource`.`errorCode`)
    ELSE NULL
  END,
  'origin', JSON_OBJECT('system', 'application')
)
WHERE `task`.`failure` IS NULL
  AND (`resource`.`errorCode` IS NOT NULL OR `resource`.`errorMessage` IS NOT NULL);

ALTER TABLE `workspace_resources`
  DROP COLUMN `errorCode`,
  DROP COLUMN `errorMessage`;

SET @failure_record_known_codes = NULL;
